[package]
name = "web-demo"
version = "0.1.0"
authors = ["Max Willsey <me@mwillsey.com>"]
edition = "2018"
description = "An demo of egraphs"
repository = "https://github.com/mwillsey/egg"
readme = "README.md"
license = "MIT"
keywords = ["egg"]
categories = ["egg"]


[dependencies]
stdweb = "0.4"
yew = "0.10.0"
log = "0.4"
env_logger = "0.7"
ordered-float = "1"
serde = { version = "1.0", features = ["derive"] }
invariants = "0.1.3"

egg = { path = "..", features = ["stdweb"] }