name: Build and Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache cargo bin
      uses: actions/cache@v2
      with:
        path: ~/.cargo/bin
        key: ${{ runner.os }}-cargo-bin
    - name: Install cargo deadlinks
      run: |
        curl -L -o ~/.cargo/bin/cargo-deadlinks https://github.com/deadlinks/cargo-deadlinks/releases/download/0.4.2/deadlinks-linux
        chmod +x ~/.cargo/bin/cargo-deadlinks
        cargo deadlinks --version
    - name: Install graphviz
      run: sudo apt-get install graphviz
    - name: Build and Test
      run: make
